name: googleapis_auth
version: 1.3.0-dev
description: Obtain Access credentials for Google services using OAuth 2.0
repository: https://github.com/dart-lang/googleapis
environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  crypto: ^3.0.0
  node_http:
    git:
      url: https://github.com/JuntoChat/node-interop.git
      path: node_http
  http_parser: ^4.0.0
  node_io: ^2.1.0

dev_dependencies:
  test: ^1.16.0

false_secrets:
- test/test_utils.dart
